export enum GlobalGameEvents {
  PLAYER_READY = 'PLAYER_READY',
  ITEM_HOVER_ENTER = 'ITEM_HOVER_ENTER',
  ITEM_HOVER_LEAVE = 'ITEM_HOVER_LEAVE',
  ITEM_CLICK = 'ITEM_CLICK',
}

export enum PlayerGameEvents {
  PLAYER_STATS_CHANGED = 'PLAYER_STATS_CHANGED',

  PLAYER_TAKE_DAMAGE = 'PLAYER_TAKE_DAMAGE',

  PLAYER_USE_MANA = 'PLAYER_USE_MANA',

  PLAYER_USING_CONSUMABLE = 'PLAYER_USING_CONSUMABLE',
  PLAYER_CONSUMABLE_USED = 'PLAYER_CONSUMABLE_USED',

  PLAYER_EQUIPMENT_CHANGED = 'PLAYER_EQUIPMENT_CHANGED',
  PLAYER_EQUIPPING_EQUIPMENT = 'PLAYER_EQUIPPING_EQUIPMENT',
  PLAYER_UNEQUIPPING_EQUIPMENT = 'PLAYER_UNEQUIPPING_EQUIPMENT',
}

export enum InventoryGameEvents {
  INVENTORY_CONSUMABLE_EMPTIED = 'INVENTORY_CONSUMABLE_EMPTIED',
}
