export enum GlobalGameEvents {
  PLAYER_READY = 'PLAYER_READY',
}

export enum PlayerGameEvents {
  PLAYER_STATS_CHANGED = 'PLAYER_STATS_CHANGED',
  PLAYER_TAKE_DAMAGE = 'PLAYER_TAKE_DAMAGE',
  PLAYER_HEAL = 'PLAYER_HEAL',
  PLAYER_USE_MANA = 'PLAYER_USE_MANA',
  PLAYER_RESTORE_MANA = 'PLAYER_RESTORE_MANA',
  PLAYER_EQUIPMENT_CHANGED = 'PLAYER_EQUIPMENT_CHANGED',
  PLAYER_EQUIPMENT_UNEQUIPPING = 'PLAYER_EQUIPMENT_UNEQUIPPING',
}
